### ISSUE TITLE
Range Check Error exception

### ISSUE THREAD

**Issue by jaclas** [bonecode/BCEditor#30]
Please drop TBCEditor on form, next compile and run application.
In empty editor please set cursor (by mouse click) to e. g. 5 char in first row then type:

123456

and press Enter.

See screenshot:
![vps_04](https://cloud.githubusercontent.com/assets/17312717/26362888/ac14d82c-3fdf-11e7-9814-67de7e98da71.png)

ps,. please check "Range checking" in project compile options

**Comment by jaclas** [comment]
Exception is raised in this line:

![vps_03](https://cloud.githubusercontent.com/assets/17312717/26363481/71c08386-3fe1-11e7-9c0a-0985b437bc93.png)

**Comment by NilsHoyer** [comment]
I've tried to reproduce this bug - without luck.

You didn't use my latest commit. On my end, that line is 6543 - not in 6636 like on your screen shot.

But you are right: I places the "Min" on the wrong position. I've fixed it and pushed the update. Can you test it for me?

**Comment by jaclas** [comment]
I try new version. Problem still exist but now in other place.
Please compile project with "Range checking" option:

![vps_05](https://cloud.githubusercontent.com/assets/17312717/26366778/97689424-3fec-11e7-85bb-0d7af5a793b0.png)

Now error is raised after typing 123456 and few times Enter and next I click mouse in center of editor:

![vps_07](https://cloud.githubusercontent.com/assets/17312717/26366948/3eaebd6c-3fed-11e7-8984-e1c8f782b899.png)

**Comment by jaclas** [comment]
![vps_08](https://cloud.githubusercontent.com/assets/17312717/26367264/414d8fde-3fee-11e7-847b-d7b457dc5139.png)

**Comment by NilsHoyer** [comment]
I've enabled the RangeChecking - but I still don't get a problem. ... strange.

But you are right: The "1 +" is wrong in this line too. In this case, I've removed it and pushed the change.

**Comment by jaclas** [comment]
Now is probably ok, errors not appears, thx
